### ISSUE TITLE
Make Rohbau::Interface a singleton

### ISSUE THREAD

**Issue by JanOwiesniak** [neopoly/rohbau#13]
I would expect the same singleton behaviour that Rohbau::ServiceFactory implements.

``` ruby
Rohbau::Interface.new === Rohbau::Interface.new # => true
```

Current implementation

``` ruby
Rohbau::Interface.new === Rohbau::Interface.new # => false
```

**Comment by splattael** [comment]
I would not expect `Rohbau::Interface.new` to be return a singleton but one could add `Rohbau::Interface.instance`.

**Comment by JanOwiesniak** [comment]
Agree `Rohbau::Interface.instance` could be one way to add this behaviour.

Nonetheless i see `Rohbau::Interface.new` just as a dynamic dispatcher around the use cases.
In my opinion a new instance does not have any benefits over a singleton.

**Comment by shluboto** [comment]
Use `Rohbau::Interface.instance` from now on.

Make sure to clear the stubbed calls in your tests by calling `Rohbau::Interface.instance.clear_stubs`
Reason: every test is using the same instance now, containing all calls
